[package]
name = "bevy_3d_physics_lite"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", default-features = false }

[dev-dependencies]
bevy = "0.14.2"
bevy-inspector-egui = "0.26.0"
