[package]
name = "bevy_3d_physics_lite"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", default-features = false }

[dev-dependencies]
bevy = "0.14.2"
bevy_rapier3d = "0.27.0"
bevy_rts_camera = "0.8.1"
bevy-inspector-egui = "0.26.0"
