[package]
name = "bevy_3d_physics_lite"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", default-features = false }

[dev-dependencies]
bevy = "0.15.3"
bevy_rapier3d = "0.29.0"
bevy_rts_camera = "0.9.1"
bevy-inspector-egui = "0.29.1"
